#!/bin/sh
# This file is in the public domain.
#
# Script for regenerating all autogenerated files.

# Usage: ./autogen.sh <module1> <module2> ...


if test -n "$GNULIB_SRCDIR"; then
  test -d "$GNULIB_SRCDIR" || {
    echo "*** GNULIB_SRCDIR is set but does not point to an existing directory." 1>&2
    exit 1
  }
fi

# Now it should contain a gnulib-tool.
GNULIB_TOOL="$GNULIB_SRCDIR/gnulib-tool"
test -f "$GNULIB_TOOL" || {
  echo "*** gnulib-tool not found." 1>&2
  exit 1
}

$GNULIB_TOOL --source-base=lib --m4-base=gnulib-m4 --import $*
mkdir -p build-aux
$GNULIB_TOOL --copy-file build-aux/ar-lib;       chmod a+x build-aux/ar-lib
$GNULIB_TOOL --copy-file build-aux/config.guess; chmod a+x build-aux/config.guess
$GNULIB_TOOL --copy-file build-aux/config.sub;   chmod a+x build-aux/config.sub

aclocal -I m4 -I gnulib-m4
autoconf
autoheader
automake -a -c
rm -rf autom4te.cache
