dnl This file is in the public domain.
dnl
dnl Configuration file - processed by autoconf.

AC_INIT([Gnulib-buildTool], [0])
AC_CONFIG_AUX_DIR([build-aux])
AM_INIT_AUTOMAKE
AC_CONFIG_HEADERS([lib/config.h])

AC_PROG_CC

gl_EARLY
gl_INIT

AC_CONFIG_FILES([Makefile])
AC_CONFIG_FILES([m4/Makefile])
AC_CONFIG_FILES([lib/Makefile])
AC_OUTPUT
